const {test}=require('node:test'),assert=require('node:assert/strict');
const {createOperationsService}=require('../outputs/operations-service');
function fixture(role='admin'){const db={projects:[{id:'p',name:'Project',contractId:'original'}],audit:[]};let writes=0;const service=createOperationsService({auth:(req,res,roles)=>{if(roles&&!roles.includes(role)){res.status=403;return null}return{id:'u',role}},json:(res,status,body)=>Object.assign(res,{status,body}),readBody:async req=>req.body,getDb:()=>db,save:()=>writes++,audit:()=>db.audit.unshift({}),getGuarantees:()=>[]});return{db,writes:()=>writes,call:async(method,path,body)=>{const r={};await service({method,body},r,['api',...path.split('/')]);return r}}}
const tender={title:'Building',entity:'Municipality',ifb:'NCB/01',deadline:'',prepared:true,guaranteeApplied:false,securityReleased:false,status:'Not awarded',securityAmount:50000,securityFee:1500};
test('import is idempotent and keeps missing deadlines / no award neutral',async()=>{const f=fixture();assert.equal((await f.call('POST','tenders/import',{rows:[tender]})).body.imported,1);assert.equal((await f.call('POST','tenders/import',{rows:[tender]})).body.skipped,1);assert.equal(f.db.publicTenders[0].deadline,'');assert.equal(f.db.publicTenders[0].status,'Not awarded')});
test('awarded project creation is explicit and repeat-safe',async()=>{const f=fixture(),t=(await f.call('POST','tenders',tender)).body.data;assert.equal((await f.call('POST','tenders/'+t.id+'/project',{contractValue:1000})).status,409);await f.call('PATCH','tenders/'+t.id,{...tender,status:'Awarded',revision:1});assert.equal((await f.call('POST','tenders/'+t.id+'/project',{})).status,422);await f.call('POST','tenders/'+t.id+'/project',{contractValue:1000});await f.call('POST','tenders/'+t.id+'/project',{contractValue:1000});assert.equal(f.db.projects.length,2);assert.equal(f.db.projects[1].contractValue,1000)});
const stock={projectId:'p',date:'2026-09-08',item:'Cement',store:'Main',unit:'bags',movement:'Received',quantity:10,reference:'GRN1',notes:'',requestId:'stock-entry-001'};
test('stock issue rejects excess and edits cannot erase consumed stock',async()=>{const f=fixture(),r=(await f.call('POST','operations/inventory',stock)).body.data;assert.equal((await f.call('POST','operations/inventory',{...stock,movement:'Issued',quantity:11,requestId:'stock-entry-002'})).status,422);await f.call('POST','operations/inventory',{...stock,movement:'Issued',quantity:5,requestId:'stock-entry-003'});assert.equal((await f.call('PATCH','operations/inventory/'+r.id,{...stock,quantity:4,revision:1})).status,422);assert.equal(f.db.operationRecords[0].quantity,10)});
test('operational entries save and edit with revision conflict protection',async()=>{const f=fixture(),values={labour:{party:'Mason',type:'Labour',description:'Wall work',quantity:2,unit:'days',rate:1000,status:'Recorded'},equipment:{equipment:'EX1',operator:'Operator',hours:8,fuel:25,serviceDate:'2026-09-20',status:'Operating'},people:{employee:'Employee',role:'Engineer',attendance:'Present',dailyRate:1000,status:'Unpaid'},quality:{type:'Safety observation',description:'Guard rail missing',owner:'Engineer',dueDate:'2026-09-09',severity:'High',status:'Open'}};for(const [kind,fields]of Object.entries(values)){const b={projectId:'p',date:'2026-09-08',notes:'',requestId:'operation-'+kind,...fields};const r=await f.call('POST','operations/'+kind,b);assert.equal(r.status,201);const id=r.body.data.id;assert.equal((await f.call('PATCH','operations/'+kind+'/'+id,{...b,notes:'Checked',revision:1})).status,200);assert.equal((await f.call('PATCH','operations/'+kind+'/'+id,{...b,revision:1})).status,409)}assert.equal(f.db.operationRecords.length,4)});
test('server blocks unauthorised operational writes',async()=>{const f=fixture('viewer');assert.equal((await f.call('POST','operations/inventory',stock)).status,403);assert.equal(f.writes(),0)});
test('invalid dates and unknown project fail without writes',async()=>{const f=fixture();assert.equal((await f.call('POST','operations/inventory',{...stock,date:'2026-02-30'})).status,422);assert.equal((await f.call('POST','operations/inventory',{...stock,projectId:'missing'})).status,422);assert.equal(f.writes(),0)});
